### ISSUE TITLE
How to use HiPPO-legS memory cell in custom pytorch model?

### ISSUE THREAD

**Issue by bonfab** [HazyResearch/hippo-code#4]
I would like to try out the HiPPO-legS memory cell and need some guidance on how to integrate it into a custom model.

Which cell in the model/memory.py should I use? Which parameters should be set? What are expected input outputs?

**Comment by albertfgu** [comment]
The exact class called by the example command in the Readme is this: https://github.com/HazyResearch/hippo-code/blob/a73ecc4e04cb340c3248dcbd679a6e541a5b4b4e/model/opcell.py#L48

You can override any of the init options in MemoryCell (https://github.com/HazyResearch/hippo-code/blob/a73ecc4e04cb340c3248dcbd679a6e541a5b4b4e/model/memory.py#L52) and its superclasses. The most common ones would probably be hidden_size and memory_size.

The interface of these cells is that of a standard RNN cell; it takes in a state and input and produces a new state and output.

There are also the classes in https://github.com/HazyResearch/hippo-code/blob/master/model/hippo.py which are the HiPPO models _without_ an RNN. These implement the basic recurrences found in the paper (e.g. equation (2) and (4)) which memorize the history of an input sequence and have no parameters. The interface of this model is a sequence to sequence model which takes in a sequence of 1-dimensional elements and produces a sequence of N-dimensional elements, where each output vector represents a compression of the history of the sequence before it.
