### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by DorotheaKolossa** [HazyResearch/hippo-code#8]
Dear all,
Thank you very much for releasing the super-interesting codebase of hippo! After successfully running the mnist experiments, I am trying to also get the imdb experiment going. But I'm getting multiple issues with versions of torch and torchtext.
Could you please update the requirements.txt (or the readme?) to show the needed versions of these packages (as would be needed for running imdb).
Many thanks,
Dorothea

**Comment by albertfgu** [comment]
Sorry for the late response; this repository is no longer used and a deprecation warning has been added.

The IMDB dataset can be found at the https://github.com/HazyResearch/state-spaces repository. Note that IMDB is actually one of the tasks in the Long Range Arena suite; the full experiment command line for an S4 model is
```
python -m train experiment=lra/s4-lra-imdb
```
This can be flexibly modified in many ways.
The dataset and model can be configured separately, e.g. the above is more or less shorthand for
```
python -m train pipeline=imdb model=s4
```
The original IMDB experiments in the HiPPO paper involved a word-level task. This can be run along with the original HiPPO-RNN for example with
```
 python -m train wandb=null pipeline=imdb dataset.level=word model=base model/layer=rnn model/layer/cell=hippo-legs
```
(this may not be the exact experiment from the original HiPPO paper, but you get the idea). At any rate the HiPPO-RNN model is still usable but is more or less deprecated in favor of S4, which is still based on HiPPO.

Feel free to file an issue in the state-spaces repo for any help running experiments there.
