### ISSUE TITLE
Values of Memory Order used?

### ISSUE THREAD

**Issue by nhansendev** [HazyResearch/hippo-code#9]
I'm trying to understand where the memory order is defined / configured in the code. For the hidden size / memory size It's mentioned in the paper that:
```
All methods have the same hidden size in our experiments. In particular, for simplicity and to reduce
hyperparameters, HiPPO variants tie the memory size N to the hidden state dimension d. The hyperparameter
N and d is also referred to as the number of hidden units.
```
Which seems to be 256, but I haven't found a clear reference to the accompanying memory order other than the low-order scenario that was described (memory order = 1).

Please let me know where this is defined. Is it the same across all experiments as well?

**Comment by albertfgu** [comment]
I believe it was either N=256 or N=512 in the original HiPPO paper, which needs to be passed in on the command line. This repository has been deprecated for the [state-spaces repo](https://github.com/HazyResearch/state-spaces). The original HiPPO-RNN models still work but are no longer used in actual experiments, as S4 is the successor. Feel free to file an issue there for any help with experiments.
